basePath: /v1
info:
  contact:
    email: support@webmeisterei.com
    name: Developers
    url: https://github.com/webmeisterei/lql_api/issues
  description: This is the LQL API for your check_mk Server.
  license:
    name: MIT
    url: https://github.com/webmeisterei/lql_api/blob/master/LICENSE
  title: LQL API
  version: "1.0"
paths: {}
swagger: "2.0"
